// Generated by CoffeeScript 1.6.3
/*
  containsサンプル
*/


(function() {
  var list;

  console.log("contains");

  list = [1, 2, 3, 4, 5];

  console.log(_.contains(list, 5));

  console.log(_.contains(list, 10));

}).call(this);
