// Generated by CoffeeScript 1.6.3
/*
  countByサンプル
*/


(function() {
  var list, res;

  console.log("countBy");

  list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  res = _.countBy(list, function(n) {
    if (n % 2 === 0) {
      return "even";
    } else {
      return "odd";
    }
  });

  console.log(res);

}).call(this);
