// Generated by CoffeeScript 1.6.3
/*
  eachサンプルコード
*/


(function() {
  _.each([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], function(n) {
    return console.log(n);
  });

  _.each({
    sample1: 1,
    sample2: 2
  }, function(key, val) {
    return console.log("" + key + "," + val);
  });

  /*
  class Hoge
    @count = 1
    @name = "hoge"
  
  
  _.each [1..3], (n) ->
    console.log("#{n}, #{Hoge.name}")
  */


}).call(this);
