// Generated by CoffeeScript 1.6.3
/*
  everyサンプル
*/


(function() {
  var list1, list2;

  console.log("every");

  list1 = [1, 2, 3, 4, 5];

  list2 = [2, 4, 6];

  console.log(_.every(list1, function(n) {
    return n % 2 === 0;
  }));

  console.log(_.every(list2, function(n) {
    return n % 2 === 0;
  }));

}).call(this);
