// Generated by CoffeeScript 1.6.3
(function() {
  var even, list, over10;

  console.log("find");

  list = [1, 2, 3, 4, 5];

  even = _.find(list, function(n) {
    return n % 2 === 0;
  });

  console.log('even is ' + even);

  over10 = _.find(list, function(n) {
    return n > 10;
  });

  console.log('over 10 ' + over10);

}).call(this);
