// Generated by CoffeeScript 1.6.3
/*
  mapサンプルコード
*/


(function() {
  console.log("map");

  console.log(_.map([1, 2, 3], function(num) {
    return num * 10;
  }));

  console.log(_.map({
    one: 1,
    two: 2,
    three: 3
  }, function(num, key) {
    return num * 5;
  }));

}).call(this);


