// Generated by CoffeeScript 1.6.3
(function() {
    var list, result;

    list = [[0, 1], [2, 3], [4, 5]];

    result = _.reduceRight(list, function(memo, n) {
        return memo.concat(n);
    }, []);

    console.log(result);

}).call(this);
