// Generated by CoffeeScript 1.6.3
/*
sizeサンプル
*/


(function() {
  var list, res;

  console.log("size");

  list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  res = _.size(list);

  console.log(res);

}).call(this);
