// Generated by CoffeeScript 1.6.3
/*
  toArrayサンプル
*/


(function() {
  var res;

  console.log("toArray");

  res = (function() {
    return _.toArray(arguments);
  })(1, 2, 3, 4, 5, true);

  console.log(res);

}).call(this);
